name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build Docker image
        run: docker build -t "$(git rev-parse --short HEAD)" .
      - name: Push to Amazon ECR
        uses: jwalton/gh-ecr-push@v1.3.3
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-1
          image: ${{ steps.vars.outputs.sha_short }}